spring:
  application:
    name: notification-service
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: ${KAFKA_GROUP_ID}
      auto-offset-reset: latest
      topics:
        - budget_alert

server:
  port: ${SERVER_PORT}