apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.keycloak.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{ toYaml .Values.deployment.keycloak.labels }}
  ports:
  - port: {{ .Values.service.keycloak.port }}
    targetPort: {{ .Values.deployment.keycloak.port }}