apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-transaction-service-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      backend: transaction
  template:
    metadata:
      name: transaction-service
      labels:
        backend: transaction
    spec:
      containers:
        - name: transaction-service
          image: prudviteja/transaction:beta-v5
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: database-transaction-cluster-ip-service:5000
            - name: DATABASE_NAME
              value: test
            - name: DATABASE_USERNAME
              value: postgres
            - name: DATABASE_PASSWORD
              value: test
            - name: KAFKA_CLUSTER
              value: kafka:9092
            - name: KAFKA_TOPIC_TRANSACTION
              value: transaction

