apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-transaction-deployment
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      database: transaction
  template:
    metadata:
      name: transaction-database
      labels:
        database: transaction
    spec:
      containers:
        - name: transaction-database
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: test
            - name: POSTGRES_DB
              value: test
