# Deployments

backend-transaction-service-deployment:
  replicas: 1
  labels:
    app: backend
  selector:
    backend: transaction
  name: transaction-service
  image: prudviteja/transaction:beta-v9
  ports:
  - containerPort: 8080
  env:
  - name: DATABASE_URL
    value: database-transaction-cluster-ip-service:5000
  - name: DATABASE_NAME
    value: test
  - name: DATABASE_USERNAME
    value: postgres
  - name: DATABASE_PASSWORD
    value: test
  - name: KAFKA_CLUSTER
    value: kafka:9092
  - name: KAFKA_TOPIC_TRANSACTION
    value: transaction
  - name: ORIGINS_ALLOWED
    value: "*"

backend-budget-service-deployment:
  replicas: 1
  labels:
    app: backend
  selector:
    backend: budget
  name: budget-service
  image: prudviteja/budget-pet:beta-v2
  ports:
  - containerPort: 8080
  env:
  - name: DATABASE_URL
    value: database-budget-cluster-ip-service:5000
  - name: DATABASE_NAME
    value: test
  - name: DATABASE_USERNAME
    value: postgres
  - name: DATABASE_PASSWORD
    value: test
  - name: KAFKA_CLUSTER
    value: kafka:9092
  - name: KAFKA_TOPIC_NOTIFICATION
    value: notification
  - name: KAFKA_TOPIC_TRANSACTION
    value: transaction
  - name: KAFKA_CONSUMER_GROUP_TRANSACTION
    value: transaction-group
  - name: ORIGINS_ALLOWED
    value: "*"

database-transaction-deployment:
  replicas: 1
  labels:
    app: database
  selector:
    database: transaction
  name: transaction-database
  image: postgres:latest
  ports:
  - containerPort: 5432
  env:
  - name: POSTGRES_USER
    value: postgres
  - name: POSTGRES_PASSWORD
    value: test
  - name: POSTGRES_DB
    value: test
  
database-budget-deployment:
  replicas: 1
  labels:
    app: database
  selector:
    database: budget
  name: budget-database
  image: postgres:latest
  ports:
  - containerPort: 5432
  env:
  - name: POSTGRES_USER
    value: postgres
  - name: POSTGRES_PASSWORD
    value: test
  - name: POSTGRES_DB
    value: test

frontend-deployment:
  replicas: 1
  labels:
    app: frontend
  selector:
    frontend: personal-expense-tracker-ui
  name: personal-expense-tracker
  image: prudviteja/personal-expense-tracker-ui:beta-v1
  ports:
  - containerPort: 80

# Services

transaction-cluster-ip-service:
  selector:
    backend: transaction
  ports:
  - port: 8080
    targetPort: 8080


database-transaction-cluster-ip-service:
  selector:
    database: transaction
  ports:
  - port: 5000
    targetPort: 5432

budget-cluster-ip-service:
  selector:
    backend: budget
  ports:
  - port: 8080
    targetPort: 8080

database-budget-cluster-ip-service:
  selector:
    database: budget
  ports:
  - port: 5000
    targetPort: 5432

frontend-cluster-ip-service:
  selector:
    frontend: personal-expense-tracker-ui
  ports:
  - port: 80
    targetPort: 80

# StatefulSets

