apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource
  labels:
    ingress: fullstack
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /api/v1/transactions
            pathType: Prefix
            backend:
              service:
                name: transaction-service
                port:
                  number: 8080
          - path: /api/v1/budgets
            pathType: Prefix
            backend:
              service:
                name: budget-service
                port:
                  number: 8080
          - path: /api/v1/notifications
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 8080