apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.keycloak.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{- toYaml .Values.deployment.keycloak.labels | nindent 6}}
  template:
    metadata:
      name: {{ .Values.deployment.keycloak.name }}
      labels:
{{- toYaml .Values.deployment.keycloak.labels | nindent 8}}
    spec:
      containers:
      - name: {{ .Values.deployment.keycloak.name }}
        image: {{ .Values.deployment.keycloak.image }}
        args: ["start-dev"]
        ports:
        - containerPort: {{ .Values.deployment.keycloak.port }}
        env:
{{- toYaml .Values.deployment.keycloak.env | nindent 12 }}