apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{- toYaml .Values.deployment.labels | nindent 6}}
  template:
    metadata:
      name: {{ .Values.deployment.name }}
      labels:
{{- toYaml .Values.deployment.labels | nindent 8}}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: {{ .Values.deployment.port }}
        env:
{{- toYaml .Values.deployment.env | nindent 12 }}