apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-budget-service-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      backend: budget
  template:
    metadata:
      name:
      labels:
        backend: budget
    spec:
      containers:
      - name: budget-service
        image: prudviteja/budget-pet:beta-v2
        ports:
          - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: database-budget-cluster-ip-service:5000
        - name: DATABASE_NAME
          value: test
        - name: DATABASE_USERNAME
          value: postgres
        - name: DATABASE_PASSWORD
          value: test
        - name: KAFKA_CLUSTER
          value: kafka:9092
        - name: KAFKA_TOPIC_NOTIFICATION
          value: notification
        - name: KAFKA_TOPIC_TRANSACTION
          value: transaction
        - name: KAFKA_CONSUMER_GROUP_TRANSACTION
          value: transaction-group
        - name: ORIGINS_ALLOWED
          value: "*"