spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5433/mydatabase
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrapServers: localhost:9092,localhost:9093,localhost:9094
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.apache.kafka.common.serialization.StringSerializer
      topic: transaction
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/pet
          jwk-set-uri: http://localhost:8443/realms/pet/protocol/openid-connect/certs # to validate token
origins:
  allowed: "*"

server:
  port: 8080