apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    backend: transaction
  ports:
    - port: 8080           # Service port
      targetPort: 8080   # Container port
