apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  # default is ClusterIP, if not mentioned
  type: ClusterIP
  selector:
    mq: zookeeper
  ports:
  - port: 2181
    targetPort: 2181