spring:
  application:
    name: auth

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: '/auth'

authorization:
  server:
    keycloak:
      tokenURL: ${KEYCLOAK_TOKEN_URL}
      grant-type: "authorization_code"
      client-id: ${KEYCLOAK_CLIENT_ID}
      client-secret: ${KEYCLOAK_CLIENT_SECRET}
      redirect-url: ${KEYCLOAK_REDIRECT_URL}