spring:
  application:
    name: budget-service
  datasource:
    url: jdbc:postgresql://{DATABASE_URL}/{DATABASE_NAME}
    username: {DATABASE_USERNAME}
    password: {DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: {SERVER_PORT}
