spring:
  application:
    name: budget-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrapServers: localhost:9092,localhost:9093,localhost:9094
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.apache.kafka.common.serialization.StringSerializer
      topic: notification
    consumer:
      bootstrapServers: localhost:9092,localhost:9093,localhost:9094
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      topic: transaction
      groupId: transaction-consumer-group

origins:
  allowed: "*"

server:
  port: 8081
