apiVersion: v1
kind: Service
metadata:
  name: personal-expense-tracker-ui-service
spec:
  type: NodePort
  selector:
    frontend: personal-expense-tracker-ui
  ports:
    - port: 80
      targetPort: 80
